#!/bin/bash

case $1 in

room2)
echo "Het wachtwoord van room2 is room2"
;;
room3)
echo "Het wachtwoord van room3 is room3"
;;
room4)
echo "Het wachtwoord van room4 is room4"
;;
room5)
echo "Het wachtwoord van room5 is room5"
;;
flag1)
echo "flag1 bestaat niet"
;;
flag2)
echo "flag2 kan je vinden in: /home/room2/flag2.txt"
;;
flag3)
echo "flag3 staat encoded in: /home/room3/flag3.txt"
;;
flag4)
echo "In de .bashrc van room4 staat een hint"
;;
flag5 | flag5.zip | flag5.txt)
echo "flag5 kan je in een zip vinden met het wachtwoord: ZmxhZzU="
echo "Let goed op de rechten die je hebt op give_pass_of_.sh!!"
;;
*)
echo "error: Include a valid variable"
;;
esac
